#!/usr/bin/env bash
# Third math WG (docs/third_math_wg.md, phase 2): offline `nvcc -Xptxas -v` of the two
# shipped tiny-M translation units with DG_FP4_MATH_WGS=2 (must stay 168 regs / 0
# spill) and =3 (152-register math budget), plus the SASS spill map of the 3-WG cubins.
#   wg3_compile.sh <outdir> [taskset cores, default 64-95]
# Uses the newest cached JIT TU of each kernel (headers come from this checkout).
set -u
out=$1; cores=${2:-64-95}
here=$(cd "$(dirname "$0")" && pwd)
mkdir -p "$out"
: > "$out/summary.txt"
cache=/root/.deep_gemm/cache
pick() { ls -td "$cache"/kernel."$1" "$cache"/kernel."$1".* 2>/dev/null | head -1; }
M=$(pick sm90_mxfp4_h200_fused_interleaved_push_pdf_lean)
Q=$(pick sm90_qoq_h200_fused_interleaved_push_pdf_lean_qis2)
echo "mxfp4_tu=$M qoq_tu=$Q" >> "$out/summary.txt"
for kv in "mxfp4=$M/kernel.cu" "qoq=$Q/kernel.cu"; do
  name=${kv%%=*}; src=${kv#*=}
  [ -f "$src" ] || { echo "$name: missing $src" >> "$out/summary.txt"; continue; }
  # A TU generated by the new host already carries "#define DG_FP4_MATH_WGS N";
  # strip it so the -D below decides.
  sed '/^#define DG_FP4_MATH_WGS /d' "$src" > "$out/$name.cu"
  ( taskset -c "$cores" bash "$here/regbudget_compile.sh" "$out/$name.cu" "$out" "${name}_w2" -DDG_FP4_MATH_WGS=2 >> "$out/summary.txt" ) &
  ( taskset -c "$cores" bash "$here/regbudget_compile.sh" "$out/$name.cu" "$out" "${name}_w3" -DDG_FP4_MATH_WGS=3 >> "$out/summary.txt" ) &
done
wait
for c in "$out"/*_w3.cubin; do
  [ -f "$c" ] && bash "$here/regbudget_sass.sh" "$c" >> "$out/summary.txt"
done
echo DONE >> "$out/summary.txt"
